fos_ck_editor:
  default_config: default
  configs:
    default:
      filebrowserBrowseRoute: elfinder
      filebrowserBrowseRouteParameters: []
      toolbar: full
      uiColor:                "#ffffff"
      forcePasteAsPlainText: true