ef_connect:
    path:  /admin/efconnect/{instance}/{homeFolder}
    defaults: { _controller: FM\ElfinderBundle\Controller\ElFinderController::loadAction, instance: default, homeFolder: '' }
elfinder:
    path: /admin/elfinder/{instance}/{homeFolder}
    defaults: { _controller: FM\ElfinderBundle\Controller\ElFinderController::showAction, instance: default, homeFolder: '' }